// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuixoWeb.Data;

#nullable disable

namespace QuixoWeb.Migrations
{
    [DbContext(typeof(QuixoDbContext))]
    partial class QuixoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuixoWeb.Models.Estadistica", b =>
                {
                    b.Property<int>("EstadisticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadisticaId"));

                    b.Property<string>("JugadorEquipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("ModoJuego")
                        .HasColumnType("tinyint");

                    b.Property<int>("PartidasGanadas")
                        .HasColumnType("int");

                    b.Property<int>("PartidasJugadas")
                        .HasColumnType("int");

                    b.HasKey("EstadisticaId");

                    b.HasIndex("ModoJuego", "JugadorEquipo")
                        .IsUnique()
                        .HasDatabaseName("IX_Estadisticas_Modo_Jugador");

                    b.ToTable("Estadisticas");

                    b.HasData(
                        new
                        {
                            EstadisticaId = 1,
                            JugadorEquipo = "Jugador1",
                            ModoJuego = (byte)2,
                            PartidasGanadas = 0,
                            PartidasJugadas = 0
                        },
                        new
                        {
                            EstadisticaId = 2,
                            JugadorEquipo = "Jugador2",
                            ModoJuego = (byte)2,
                            PartidasGanadas = 0,
                            PartidasJugadas = 0
                        },
                        new
                        {
                            EstadisticaId = 3,
                            JugadorEquipo = "EquipoA",
                            ModoJuego = (byte)4,
                            PartidasGanadas = 0,
                            PartidasJugadas = 0
                        },
                        new
                        {
                            EstadisticaId = 4,
                            JugadorEquipo = "EquipoB",
                            ModoJuego = (byte)4,
                            PartidasGanadas = 0,
                            PartidasJugadas = 0
                        });
                });

            modelBuilder.Entity("QuixoWeb.Models.Jugada", b =>
                {
                    b.Property<int>("JugadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugadaId"));

                    b.Property<int>("ColumnaDestino")
                        .HasColumnType("int");

                    b.Property<int>("ColumnaOrigen")
                        .HasColumnType("int");

                    b.Property<string>("EstadoTablero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilaDestino")
                        .HasColumnType("int");

                    b.Property<int>("FilaOrigen")
                        .HasColumnType("int");

                    b.Property<int>("JugadorActual")
                        .HasColumnType("int");

                    b.Property<int>("NumeroJugada")
                        .HasColumnType("int");

                    b.Property<byte?>("OrientacionPunto")
                        .HasColumnType("tinyint");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TiempoTranscurrido")
                        .HasColumnType("time");

                    b.HasKey("JugadaId");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("IX_Jugadas_PartidaId");

                    b.ToTable("Jugadas");
                });

            modelBuilder.Entity("QuixoWeb.Models.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidaId"));

                    b.Property<string>("EquipoGanador")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("EnCurso");

                    b.Property<DateTime>("FechaHoraCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("int");

                    b.Property<byte>("ModoJuego")
                        .HasColumnType("tinyint");

                    b.Property<TimeSpan>("TiempoTranscurrido")
                        .HasColumnType("time");

                    b.HasKey("PartidaId");

                    b.HasIndex("FechaHoraCreacion")
                        .IsDescending()
                        .HasDatabaseName("IX_Partidas_Fecha");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("QuixoWeb.Models.Jugada", b =>
                {
                    b.HasOne("QuixoWeb.Models.Partida", "Partida")
                        .WithMany("Jugadas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("QuixoWeb.Models.Partida", b =>
                {
                    b.Navigation("Jugadas");
                });
#pragma warning restore 612, 618
        }
    }
}
